from typing import Dict, NamedTuple, Optional
from BaseClasses import Location

class SettlersLocation(Location):
    game = "SettlersHeritageOfKings"

class SettlersLocationData(NamedTuple):
    region: str
    address: Optional[int]
    questtype: str

location_table = {
    "thalgrund_save_village": SettlersLocationData(address=101, region='Thalgrund', questtype='MainQuest'),
    "thalgrund_speak_with_priest": SettlersLocationData(address=102, region='Thalgrund', questtype='MainQuest'),
    "thalgrund_sword_mayor": SettlersLocationData(address=103, region='Thalgrund', questtype='MainQuest'),
    "thalgrund_bow_mayor": SettlersLocationData(address=104, region='Thalgrund', questtype='MainQuest'),
    "thalgrund_build_barracks": SettlersLocationData(address=105, region='Thalgrund', questtype='MainQuest'),
    "thalgrund_leonardo": SettlersLocationData(address=106, region='Thalgrund', questtype='MainQuest'),
    "thalgrund_ring_quest": SettlersLocationData(address=107, region='Thalgrund', questtype='SideQuest'),
    "thalgrund_river_yacht_villager": SettlersLocationData(address=108, region='Thalgrund', questtype='SideQuest'),
    "thalgrund_victory": SettlersLocationData(address=109, region='Thalgrund', questtype='MainQuest'),

    "villageattack_save_village": SettlersLocationData(address=110, region='VillageAttack', questtype='MainQuest'),
    "villageattack_camps_cleared": SettlersLocationData(address=111, region='VillageAttack', questtype='MainQuest'),
    "villageattack_speak_with_leonardo": SettlersLocationData(address=112, region='VillageAttack', questtype='MainQuest'),
    "villageattack_troop_tribute": SettlersLocationData(address=113, region='VillageAttack', questtype='SideQuest'),
    "villageattack_erec_arrival": SettlersLocationData(address=114, region='VillageAttack', questtype='MainQuest'),
    "villageattack_victory": SettlersLocationData(address=115, region='VillageAttack', questtype='MainQuest'),

    "crawford_west_ballista": SettlersLocationData(address=116, region='Crawford', questtype='MainQuest'),
    "crawford_east_ballista": SettlersLocationData(address=117, region='Crawford', questtype='MainQuest'),
    "crawford_north_ballista": SettlersLocationData(address=118, region='Crawford', questtype='MainQuest'),
    "crawford_west_base": SettlersLocationData(address=119, region='Crawford', questtype='MainQuest'),
    "crawford_east_base": SettlersLocationData(address=120, region='Crawford', questtype='MainQuest'),
    "crawford_open_gate": SettlersLocationData(address=121, region='Crawford', questtype='MainQuest'),
    "crawford_victory": SettlersLocationData(address=122, region='Crawford', questtype='MainQuest'),
    "crawford_pay_dovbar": SettlersLocationData(address=123, region='Crawford', questtype='SideQuest'),
    "crawford_help_leonardo": SettlersLocationData(address=124, region='Crawford', questtype='SideQuest'),

    "cleycourt_reach_barmecia": SettlersLocationData(address=125, region='Cleycourt', questtype='MainQuest'),
    "cleycourt_collect_key": SettlersLocationData(address=126, region='Cleycourt', questtype='MainQuest'),
    "cleycourt_capture_ari": SettlersLocationData(address=127, region='Cleycourt', questtype='MainQuest'),
    "cleycourt_build_uni": SettlersLocationData(address=128, region='Cleycourt', questtype='MainQuest'),
    "cleycourt_cleycourt_view": SettlersLocationData(address=129, region='Cleycourt', questtype='SideQuest'),
    "cleycourt_barmecia_view": SettlersLocationData(address=130, region='Cleycourt', questtype='SideQuest'),
    "cleycourt_victory": SettlersLocationData(address=131, region='Cleycourt', questtype='MainQuest'),

    "flood_gather_wood": SettlersLocationData(address=132, region='Flood', questtype='MainQuest'),
    "flood_gather_clay": SettlersLocationData(address=133, region='Flood', questtype='MainQuest'),
    "flood_gather_iron": SettlersLocationData(address=134, region='Flood', questtype='MainQuest'),
    "flood_get_ari": SettlersLocationData(address=135, region='Flood', questtype='MainQuest'),
    "flood_find_key": SettlersLocationData(address=136, region='Flood', questtype='MainQuest'),
    "flood_hand_in_key": SettlersLocationData(address=137, region='Flood', questtype='MainQuest'),
    "flood_victory": SettlersLocationData(address=138, region='Flood', questtype='MainQuest'),

    "barmecia_market_burning": SettlersLocationData(address=139, region='Barmecia', questtype='MainQuest'),
    "barmecia_market_bandits": SettlersLocationData(address=140, region='Barmecia', questtype='MainQuest'),
    "barmecia_reach_barmecia": SettlersLocationData(address=141, region='Barmecia', questtype='MainQuest'),
    "barmecia_reach_cleycourt": SettlersLocationData(address=142, region='Barmecia', questtype='MainQuest'),
    "barmecia_east_bandit_camp": SettlersLocationData(address=143, region='Barmecia', questtype='SideQuest'),
    "barmecia_build_sulfur_mine": SettlersLocationData(address=144, region='Barmecia', questtype='MainQuest'),
    "barmecia_victory": SettlersLocationData(address=145, region='Barmecia', questtype='MainQuest'),

    "folklung_speak_with_pilgrim": SettlersLocationData(address=146, region='Folklung', questtype='MainQuest'),
    "folklung_destroy_enemies": SettlersLocationData(address=147, region='Folklung', questtype='MainQuest'),
    "folklung_leader": SettlersLocationData(address=148, region='Folklung', questtype='MainQuest'),
    "folklung_rock_destroyed": SettlersLocationData(address=149, region='Folklung', questtype='MainQuest'),
    "folklung_victory": SettlersLocationData(address=150, region='Folklung', questtype='MainQuest'),

    "norfolk_defend_messenger": SettlersLocationData(address=151, region='Norfolk', questtype='MainQuest'),
    "norfolk_waterfall": SettlersLocationData(address=152, region='Norfolk', questtype='MainQuest'),
    "norfolk_behind_enemy_base": SettlersLocationData(address=153, region='Norfolk', questtype='MainQuest'),
    "norfolk_barbarian_base": SettlersLocationData(address=154, region='Norfolk', questtype='SideQuest'),
    "norfolk_kerberos_base": SettlersLocationData(address=155, region='Norfolk', questtype='SideQuest'),
    "norfolk_winter": SettlersLocationData(address=156, region='Norfolk', questtype='MainQuest'),
    "norfolk_victory": SettlersLocationData(address=157, region='Norfolk', questtype='MainQuest'),

    "kaloix_defeat_bandits_left": SettlersLocationData(address=158, region='Kaloix', questtype='SideQuest'),
    "kaloix_defeat_bandits_right": SettlersLocationData(address=159, region='Kaloix', questtype='SideQuest'),
    "kaloix_port_tribute": SettlersLocationData(address=160, region='Kaloix', questtype='MainQuest'),
    "kaloix_stone_mine": SettlersLocationData(address=161, region='Kaloix', questtype='SideQuest'),
    "kaloix_clay_mine": SettlersLocationData(address=162, region='Kaloix', questtype='SideQuest'),
    "kaloix_iron_mine": SettlersLocationData(address=163, region='Kaloix', questtype='SideQuest'),
    "kaloix_sulfur_mine": SettlersLocationData(address=164, region='Kaloix', questtype='SideQuest'),
    "kaloix_tourte_solution": SettlersLocationData(address=165, region='Kaloix', questtype='SideQuest'),
    "kaloix_victory": SettlersLocationData(address=166, region='Kaloix', questtype='MainQuest'),

    "plague_pilgrim": SettlersLocationData(address=167, region='Plague', questtype='MainQuest'),
    "plague_helias": SettlersLocationData(address=168, region='Plague', questtype='MainQuest'),
    "plague_village_center_winter": SettlersLocationData(address=169, region='Plague', questtype='MainQuest'),
    "plague_village_center_plague_village": SettlersLocationData(address=170, region='Plague', questtype='MainQuest'),
    "plague_dario_archers": SettlersLocationData(address=171, region='Plague', questtype='SideQuest'),
    "plague_erec_swords": SettlersLocationData(address=172, region='Plague', questtype='SideQuest'),
    "plague_salim_cannons": SettlersLocationData(address=173, region='Plague', questtype='SideQuest'),
    "plague_victory": SettlersLocationData(address=174, region='Plague', questtype='MainQuest'),

    "old_kings_castle_door_key": SettlersLocationData(address=175, region='OldKingsCastle', questtype='MainQuest'),
    "old_kings_castle_andalla": SettlersLocationData(address=176, region='OldKingsCastle', questtype='MainQuest'),
    "old_kings_castle_bandits_front": SettlersLocationData(address=177, region='OldKingsCastle', questtype='SideQuest'),
    "old_kings_castle_bandits_rock": SettlersLocationData(address=178, region='OldKingsCastle', questtype='SideQuest'),
    "old_kings_castle_bandits_castle": SettlersLocationData(address=179, region='OldKingsCastle', questtype='SideQuest'),
    "old_kings_castle_reach_castle": SettlersLocationData(address=180, region='OldKingsCastle', questtype='MainQuest'),
    "old_kings_castle_liberate_village": SettlersLocationData(address=181, region='OldKingsCastle', questtype='MainQuest'),
    "old_kings_castle_andalla_tribute": SettlersLocationData(address=182, region='OldKingsCastle', questtype='SideQuest'),
    "old_kings_castle_castle_tribute": SettlersLocationData(address=183, region='OldKingsCastle', questtype='MainQuest'),
    "old_kings_castle_winter_base": SettlersLocationData(address=184, region='OldKingsCastle', questtype='SideQuest'),
    "old_kings_castle_summer": SettlersLocationData(address=185, region='OldKingsCastle', questtype='MainQuest'),
    "old_kings_castle_leonardo_tribute": SettlersLocationData(address=186, region='OldKingsCastle', questtype='SideQuest'),
    "old_kings_castle_victory": SettlersLocationData(address=187, region='OldKingsCastle', questtype='MainQuest'),

    "cloudy_mountains_bandits": SettlersLocationData(address=188, region='CloudyMountains', questtype='SideQuest'),
    "cloudy_mountains_bandits_stoneville": SettlersLocationData(address=189, region='CloudyMountains', questtype='SideQuest'),
    "cloudy_mountains_border_rocks": SettlersLocationData(address=190, region='CloudyMountains', questtype='MainQuest'),
    "cloudy_mountains_beautifications": SettlersLocationData(address=191, region='CloudyMountains', questtype='MainQuest'),
    "cloudy_mountains_prospering_village": SettlersLocationData(address=192, region='CloudyMountains', questtype='MainQuest'),
    "cloudy_mountains_mordred_base": SettlersLocationData(address=193, region='CloudyMountains', questtype='SideQuest'),
    "cloudy_mountains_winter": SettlersLocationData(address=194, region='CloudyMountains', questtype='MainQuest'),
    "cloudy_mountains_victory": SettlersLocationData(address=195, region='CloudyMountains', questtype='MainQuest'),

    "evelance_destroy_kerberos": SettlersLocationData(address=196, region='Evelance', questtype='MainQuest'),
    "evelance_reach_tendrel": SettlersLocationData(address=197, region='Evelance', questtype='MainQuest'),
    "evelance_cathedral": SettlersLocationData(address=198, region='Evelance', questtype='SideQuest'),
    "evelance_rescue_daughter": SettlersLocationData(address=199, region='Evelance', questtype='MainQuest'),
    "evelance_sulfur_mines": SettlersLocationData(address=200, region='Evelance', questtype='SideQuest'),
    "evelance_victory": SettlersLocationData(address=201, region='Evelance', questtype='MainQuest'),

    "wasteland_destroy_highport": SettlersLocationData(address=202, region='Wasteland', questtype='SideQuest'),
    "wasteland_destroy_outpost_prison": SettlersLocationData(address=203, region='Wasteland', questtype='SideQuest'),
    "wasteland_destroy_outpost_ashford": SettlersLocationData(address=204, region='Wasteland', questtype='SideQuest'),
    "wasteland_village_weathermaster": SettlersLocationData(address=205, region='Wasteland', questtype='SideQuest'),
    "wasteland_winter": SettlersLocationData(address=206, region='Wasteland', questtype='MainQuest'),
    "wasteland_village_center_winter": SettlersLocationData(address=207, region='Wasteland', questtype='MainQuest'),
    "wasteland_village_rain": SettlersLocationData(address=208, region='Wasteland', questtype='MainQuest'),
    "wasteland_soldiers_rescue": SettlersLocationData(address=209, region='Wasteland', questtype='MainQuest'),
    "wasteland_village_build_residences": SettlersLocationData(address=210, region='Wasteland', questtype='MainQuest'),
    "wasteland_victory": SettlersLocationData(address=211, region='Wasteland', questtype='MainQuest'),

    "battleofevelance_reinforcement_infantry": SettlersLocationData(address=212, region='BattleOfEvelance', questtype='MainQuest'),
    "battleofevelance_reinforcement_cavalry": SettlersLocationData(address=213, region='BattleOfEvelance', questtype='MainQuest'),
    "battleofevelance_tribute_view": SettlersLocationData(address=214, region='BattleOfEvelance', questtype='SideQuest'),
    "battleofevelance_tribute_cannon": SettlersLocationData(address=215, region='BattleOfEvelance', questtype='SideQuest'),
    "battleofevelance_tribute_secretpath": SettlersLocationData(address=216, region='BattleOfEvelance', questtype='SideQuest'),
    "battleofevelance_tribute_weathermaker": SettlersLocationData(address=217, region='BattleOfEvelance', questtype='SideQuest'),
    "battleofevelance_outpost": SettlersLocationData(address=218, region='BattleOfEvelance', questtype='MainQuest'),
    "battleofevelance_victory": SettlersLocationData(address=219, region='BattleOfEvelance', questtype='MainQuest'),
}